name: Slack Notification on Label Change for Subscribed User

on:
  issues:
    types:
      - labeled
      - unlabeled
  issue_comment:
    types:
      - created

jobs:
  notify-slack:
    runs-on: ubuntu-latest

    steps:
      - name: Check if label added or comment mentions user
        if: (github.event.action == 'labeled' && contains(github.event.issue.labels.*.name, 'wontfix') || contains(github.event.issue.labels.*.name, 'bug'))
        run: |
          echo "Label added: ${{ github.event.label.name }}"
          echo "Issue: ${{ github.event.issue.html_url }}"
          echo "Comment created by: ${{ github.actor }}"
        continue-on-error: true

      - name: Send Slack Notification
        if: steps.notify-slack.outcome == 'success'
        uses: rtCamp/action-slack-notify@v2
        with:
          fields: issue:${{ github.event.issue.number }}
          fields_mapping: issue:${{ github.event.issue.html_url }}
          text: 'Label change on issue: ${{ github.event.issue.html_url }}'

        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
