name: Slack Notification on Label Change for Subscribed User

on:
  issues:
    types:
      - labeled
      - unlabeled
  issue_comment:
    types:
      - created

jobs:
  notify-slack:
    runs-on: ubuntu-latest

    steps:
      - name: Check if label added or comment mentions user
        if: (github.event.action == 'labeled' && contains(github.event.issue.labels.*.name, 'wontfix'))
        run: |
          echo "Label added: ${{ github.event.label.name }}"
          echo "Issue: ${{ github.event.issue.html_url }}"
          echo "Comment created by: ${{ github.actor }}"
        continue-on-error: true
  slack-workflow-status:
    if: always()
    name: Post Workflow Status To Slack
    needs:
      - notify-slack
    runs-on: ubuntu-latest
    steps:
      - name: Slack Workflow Notification
        id: slack 
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: '#project-qa-updates'
          payload: |
                {
                  "text": "GitHub Action build result: Label change on issue: ${{ github.event.issue.html_url }}",
                  "blocks": [
                 {
                   "type": "section",
                   "text": {
                     "type": "mrkdwn",
                     "text": "GitHub Action build result: Label change on issue: ${{ github.event.issue.html_url }}"
                   }
                 }
                ]
                }     
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
