name: Multi-Job CI

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running job 1"

  job2:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1

  job3:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running job 3"

  job4:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1 # Another failure

  job5:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running job 5"

  report:
    runs-on: ubuntu-latest
    needs: [job1, job2, job3, job4, job5]
    if: always() # Always run, even if dependencies fail
    steps:
      - name: Report Results
        run: |
          echo "Job 1: ${{ needs.job1.result }}"
          echo "Job 2: ${{ needs.job2.result }}"
          echo "Job 3: ${{ needs.job3.result }}"
          echo "Job 4: ${{ needs.job4.result }}"
          echo "Job 5: ${{ needs.job5.result }}"

          if [ "${{ needs.job2.result }}" == "failure" ]; then
            echo "❌ Job 2 failed, notifying owner..."
          fi

          if [ "${{ needs.job4.result }}" == "failure" ]; then
            echo "❌ Job 4 failed, notifying owner..."
          fi
